name: pro_video_editor_example
description: "Demonstrates how to use the pro_video_editor plugin."
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  pro_video_editor:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0
 

flutter:
  uses-material-design: true
  assets:
    - assets/demo.mp4