name: pro_video_editor
description: "A Flutter video editor: Seamlessly enhance your videos with user-friendly editing features."
version: 0.1.3
homepage: https://github.com/hm21/pro_video_editor/
repository: https://github.com/hm21/pro_video_editor/
documentation: https://github.com/hm21/pro_video_editor/
funding:
  - https://github.com/sponsors/hm21


topics:
  - video-editor
  - video
  - movie
  - editor

screenshots:
  - description: "Showcase from the video editor with the grounded design"
    path: assets/showcase.jpg
  - description: "Showcase from the video editor with simple design"
    path: assets/showcase1.jpg

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
 
  plugin_platform_interface: ^2.1.8
  http: ^1.4.0
  mime: ^2.0.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0
  mockito: ^5.4.6
  network_image_mock: ^2.1.1

flutter:
  plugin:
    platforms:
      android:
        package: ch.waio.pro_video_editor
        pluginClass: ProVideoEditorPlugin
      ios:
        pluginClass: ProVideoEditorPlugin
      linux:
        pluginClass: ProVideoEditorPlugin
      macos:
        pluginClass: ProVideoEditorPlugin
      windows:
        pluginClass: ProVideoEditorPluginCApi
      web:
        pluginClass: ProVideoEditorWeb
        fileName: pro_video_editor_web.dart
